# Generated by Django 4.0.3 on 2022-04-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response_state',
            field=models.BooleanField(default=False),
        ),
    ]
